name: SmokeTest

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # at least support HEAD~1 for testing
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Prepare test source
        run: |
          curl -L  https://github.com/sourcegraph/lsif-go/releases/download/v1.9.3/src_linux_amd64 -o /usr/local/bin/lsif-go
          chmod +x /usr/local/bin/lsif-go
          lsif-go -v

      - name: Test
        run: go test -v ./... -coverprofile=coverage.txt -coverpkg=./...

      - name: Cmd Test
        run: |
          make
          ./srctx diff --outputHtml output.html

      - name: Build Extra Dep
        run: |
          # scip-java
          curl -fL "https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz" | gzip -d > coursier \
            && chmod +x coursier \
            && ./coursier setup -y \
            && ./coursier bootstrap --standalone --bat=true -o scip-java com.sourcegraph:scip-java_2.13:0.8.18 --main com.sourcegraph.scip_java.ScipJava

      - name: Third Party Test (Golang)
        run: |
          git clone https://github.com/gin-gonic/gin --depth=2
          cd gin
          lsif-go -v
          ../srctx diff --outputHtml ../golang.html
          cd ..

      - name: Third Party Test (Java)
        run: |
          git clone https://github.com/junit-team/junit4 --depth=2
          cd junit4
          ../scip-java index -- package -DskipTests --batch-mode --errors --settings .github/workflows/settings.xml
          ../srctx diff --scip ./index.scip --outputHtml ../java.html
          cd ..

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
