name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Prepare test source
        run: |
          curl -L  https://github.com/sourcegraph/lsif-go/releases/download/v1.9.3/src_linux_amd64 -o /usr/local/bin/lsif-go
          chmod +x /usr/local/bin/lsif-go
          lsif-go -v
      - name: Test
        run: |
          go test -v ./...
      - name: Build
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: 1.19
          pkg: cmd/srctx
          dest: build
          prefix: srctx
          targets: windows/amd64,linux/amd64,linux/arm64,darwin/amd64,darwin/arm64
          v: true
          x: false
          ldflags: -s -w
          buildmode: default
      - name: Build Full CI Package
        run: |
          # scip-java
          curl -fLo coursier https://git.io/coursier-cli \
            && chmod +x coursier \
            && ./coursier bootstrap --standalone -o scip-java com.sourcegraph:scip-java_2.13:0.8.18 --main com.sourcegraph.scip_java.ScipJava
          
          # zip for CI/docker
          cp ./build/srctx-linux-amd64 ./srctx
          zip srctx-linux-amd64-full.zip scip-java ./srctx

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/srctx-*
            srctx-linux-amd64-full.zip
