name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Test
        run: |
          go test -v ./...
      - name: Build
        run: |
          make build_linux_amd64
          make build_windows_amd64
          make build_macos_amd64
          make build_macos_arm64
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            srctx_linux_amd64
            srctx_windows_amd64
            srctx_macos_amd64
            srctx_macos_arm64
